on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.6]
        
    steps:
      - name: tests
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - run: |
        python -V
        python hello.py
