on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.6]
        
    steps:
      - name: install python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: python version
        run: python -V
      - name: run hello.py
        run: python hello.py
