on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.6]
        
    steps:
      - uses: actions/checkout@master
      - name: install python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: run python
        run: |
          python -V
          python hello.py
      - name: install php
        uses: flc1125/tests@master
      - name: run php
        run: php hello.php
