name: php-tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@master
      - name: run php
        run: |
          php hello.php
      - name: push
        run: |
          touch ./1.log
          git checkout -b other
          git push origin other --force
    
    services:
      redis:
        image: redis:5.0.6-alpine
        ports:
          - 6379:6379
      php:
        image: php:7.2.9
