name: python-tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.6]
        
    steps:
      - uses: actions/checkout@master
      - name: install python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: run python
        run: |
          python -V
          python hello.py
          sudo mkdir -p /usr/local/ssdb
          sudo touch /usr/local/ssdb/log.txt
